apiVersion: messaging.eclipse.org/v1alpha1
kind: Mosquitto
metadata:
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto-sample
    app.kubernetes.io/part-of: mosquitto-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mosquitto-operator
  name: mosquitto-sample
spec:
  authEnabled: false
  authSecret: notenabled
  persist: false  
